# Generated by Django 5.0.3 on 2024-12-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, help_text='Especialización del profesor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Estudiante'), ('moderator', 'Profesor'), ('admin', 'Administrador')], default='student', max_length=10),
        ),
    ]
