# Generated by Django 5.0.3 on 2024-12-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
