# Generated by Django 5.1.4 on 2024-12-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_text',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido del documento'),
        ),
    ]
