# Generated by Django 5.0.3 on 2024-12-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0002_document_content_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_text',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido del texto'),
        ),
    ]
